substitutions:
  name: esp32-bedroom-bed
  friendly_name: Bedroom Bed
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  areas:
    - id: bedroom_area
      name: Bedroom

api:
  encryption:
    key: !secret bedroom_bed_api_encryption_key

time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

web_server:
  port: 80
  version: 3
  sorting_groups:
    - id: bed_controls
      name: Bed Controls
      sorting_weight: 10
    - id: bed_info
      name: Bed Information
      sorting_weight: 20
    - id: system_info
      name: System
      sorting_weight: 30

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic-c3.yaml@main
  left_bed: !include
    file: furnimove_bed_device.yaml
    vars:
      device_name: Left
      device_id: left
      device_mac: 00:00:00:00:00:00
      area_id: bedroom_area
  right_bed: !include
    file: furnimove_bed_device.yaml
    vars:
      device_name: Right
      device_id: right
      device_mac: AA:AA:AA:AA:AA:AA
      area_id: bedroom_area

sensor:
  - platform: uptime
    name: Uptime
    type: timestamp
    entity_category: diagnostic
    web_server:
      sorting_group_id: system_info
      sorting_weight: 10
  - platform: wifi_signal
    name: Wi-Fi Signal
    entity_category: diagnostic
    update_interval: 60s
    web_server:
      sorting_group_id: system_info
      sorting_weight: 20

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
    web_server:
      sorting_group_id: system_info
      sorting_weight: 40

  # Extend buttons from esphome.bluetooth-proxy.
  - id: !extend button_safe_mode
    entity_category: diagnostic
    web_server:
      sorting_group_id: system_info
      sorting_weight: 50
  - id: !extend factory_reset_btn
    entity_category: diagnostic
    web_server:
      sorting_group_id: system_info
      sorting_weight: 60

esp32_ble:
  max_connections: 5
  connection_timeout: 10s

esp32_ble_tracker:
  # Optional debugging.
  on_ble_advertise:
    - mac_address:
        - 00:00:00:00:00:00
        - AA:AA:AA:AA:AA:AA
      then:
        - lambda: |-
            ESP_LOGD("ble_adv", "New BLE device");
            ESP_LOGD("ble_adv", "  address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  name: %s", x.get_name().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
                ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
